USB_VID = 0x303A
USB_PID = 0x82C5
# BLE board identification
CIRCUITPY_CREATOR_ID = 0x000C303A
CIRCUITPY_CREATION_ID = 0x00C50001
USB_PRODUCT = "ESP32-C5-DevKitC-1-N8R8"
USB_MANUFACTURER = "Espressif"
IDF_TARGET = esp32c5
CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 4MB
FLASH_MODE = dio
FLASH_SIZE = 4MB
CIRCUITPY_NEOPIXEL_WRITE = 1
