USB_VID = 0x303A
USB_PID = 0x82C5
USB_PRODUCT = "ESP32-C5-DevKitC-1-N8R8"
USB_MANUFACTURER = "Espressif"

IDF_TARGET = esp32c5

CIRCUITPY_ESP_FLASH_MODE = dio
CIRCUITPY_ESP_FLASH_FREQ = 80m
CIRCUITPY_ESP_FLASH_SIZE = 8MB

# Fallbacks in case Makefile expects non-prefixed variables
FLASH_MODE = dio
FLASH_SIZE = 8MB

CIRCUITPY_NEOPIXEL_WRITE = 1

# PSRAM temporarily disabled for initial bringup
# CIRCUITPY_ESP_PSRAM_SIZE = 8MB
# CIRCUITPY_ESP_PSRAM_MODE = qio
# CIRCUITPY_ESP_PSRAM_FREQ = 40m
