USB_VID = 0x303A
USB_PID = 0x826D
USB_PRODUCT = "Waveshare ESP32-C5 LCD 1.47"
USB_MANUFACTURER = "Waveshare"

IDF_TARGET = esp32c5

CIRCUITPY_ESP_FLASH_MODE = qio
CIRCUITPY_ESP_FLASH_SIZE = 4MB

# Displayio & BusDisplay support
CIRCUITPY_BUSDISPLAY = 1
CIRCUITPY_FOURWIRE = 1
